import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import { NuqsAdapter } from "nuqs/adapters/next/app";
import { AppSidebar } from "@/components/sidebar/app-sidebar";
import { Breadcrumbs } from "@/components/sidebar/breadcrumbs";
import { CustomMenu } from "@/components/sidebar/custom-menu";
import {
  Avatar,
  AvatarFallback,
  AvatarImage,
} from "@/components/ui/base-avatar";
import {
  SidebarInset,
  SidebarProvider,
  SidebarTrigger,
} from "@/components/ui/sidebar";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.variable}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NuqsAdapter>
          <SidebarProvider>
            <AppSidebar />
            <SidebarInset>
              <header className="flex h-[54px] px-4 shrink-0 border-b items-center gap-2 transition-[width,height] ease-linear group-has-data-[collapsible=icon]/sidebar-wrapper:h-[54px]">
                <div className="flex items-center justify-between w-full">
                  <div className="flex items-center gap-2">
                    <SidebarTrigger />
                    <Breadcrumbs />
                  </div>
                  <div className="flex items-center gap-2">
                    <CustomMenu />
                    <Avatar className="size-8">
                      <AvatarImage src="https://github.com/shadcn.png" />
                      <AvatarFallback>CN</AvatarFallback>
                    </Avatar>
                  </div>
                </div>
              </header>
              {children}
            </SidebarInset>
          </SidebarProvider>
        </NuqsAdapter>
      </body>
    </html>
  );
}
